Scene = 'Game'

[[Entities]]

    [[Entities.Floor]]
    _tag = 'Floor'

    [[Entities.Floor]]
    _position = [ 0.0, -5.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 10.0, 10.0, 10.0 ]

    [[Entities.Floor]]

        [[Entities.Floor._colliders]]
        _colliderCollisionMask = 65535
        _colliderMaterial = [ 0.30000001192092896, 0.5, 1.0 ]
        _colliderPosition = [ 0.0, 0.0, 0.0 ]
        _colliderRotation = [ 0.0, -0.0, 0.0 ]
        _colliderSpecificData = [ [ '_boxCollider', [ '_halfSize', [ 10.0, 0.10000000149011612, 10.0 ] ] ] ]
        _shapeType = 1

    [[Entities.Floor]]
    _modelPath = 'Plane.obj'

    [[Entities.Floor]]
    _active = true
    _bodyType = 0
    _mass = 1.0
    _useGravity = true

[[Entities]]

    [[Entities.Entity49]]
    _tag = 'Entity49'

    [[Entities.Entity49]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity48]]
    _tag = 'Entity48'

    [[Entities.Entity48]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity47]]
    _tag = 'Entity47'

    [[Entities.Entity47]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity46]]
    _tag = 'Entity46'

    [[Entities.Entity46]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity45]]
    _tag = 'Entity45'

    [[Entities.Entity45]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity44]]
    _tag = 'Entity44'

    [[Entities.Entity44]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity43]]
    _tag = 'Entity43'

    [[Entities.Entity43]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity42]]
    _tag = 'Entity42'

    [[Entities.Entity42]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity41]]
    _tag = 'Entity41'

    [[Entities.Entity41]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity40]]
    _tag = 'Entity40'

    [[Entities.Entity40]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity39]]
    _tag = 'Entity39'

    [[Entities.Entity39]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity38]]
    _tag = 'Entity38'

    [[Entities.Entity38]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity37]]
    _tag = 'Entity37'

    [[Entities.Entity37]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity36]]
    _tag = 'Entity36'

    [[Entities.Entity36]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity35]]
    _tag = 'Entity35'

    [[Entities.Entity35]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity34]]
    _tag = 'Entity34'

    [[Entities.Entity34]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity33]]
    _tag = 'Entity33'

    [[Entities.Entity33]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity32]]
    _tag = 'Entity32'

    [[Entities.Entity32]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity31]]
    _tag = 'Entity31'

    [[Entities.Entity31]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity30]]
    _tag = 'Entity30'

    [[Entities.Entity30]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity29]]
    _tag = 'Entity29'

    [[Entities.Entity29]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity28]]
    _tag = 'Entity28'

    [[Entities.Entity28]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity27]]
    _tag = 'Entity27'

    [[Entities.Entity27]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity26]]
    _tag = 'Entity26'

    [[Entities.Entity26]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity25]]
    _tag = 'Entity25'

    [[Entities.Entity25]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity24]]
    _tag = 'Entity24'

    [[Entities.Entity24]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity23]]
    _tag = 'Entity23'

    [[Entities.Entity23]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity22]]
    _tag = 'Entity22'

    [[Entities.Entity22]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity21]]
    _tag = 'Entity21'

    [[Entities.Entity21]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity20]]
    _tag = 'Entity20'

    [[Entities.Entity20]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity19]]
    _tag = 'Entity19'

    [[Entities.Entity19]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity18]]
    _tag = 'Entity18'

    [[Entities.Entity18]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity17]]
    _tag = 'Entity17'

    [[Entities.Entity17]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity16]]
    _tag = 'Entity16'

    [[Entities.Entity16]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity15]]
    _tag = 'Entity15'

    [[Entities.Entity15]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity14]]
    _tag = 'Entity14'

    [[Entities.Entity14]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity13]]
    _tag = 'Entity13'

    [[Entities.Entity13]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity12]]
    _tag = 'Entity12'

    [[Entities.Entity12]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity11]]
    _tag = 'Entity11'

    [[Entities.Entity11]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity10]]
    _tag = 'Entity10'

    [[Entities.Entity10]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity9]]
    _tag = 'Entity9'

    [[Entities.Entity9]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity8]]
    _tag = 'Entity8'

    [[Entities.Entity8]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity7]]
    _tag = 'Entity7'

    [[Entities.Entity7]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity6]]
    _tag = 'Entity6'

    [[Entities.Entity6]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity5]]
    _tag = 'Entity5'

    [[Entities.Entity5]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity4]]
    _tag = 'Entity4'

    [[Entities.Entity4]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity3]]
    _tag = 'Entity3'

    [[Entities.Entity3]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity2]]
    _tag = 'Entity2'

    [[Entities.Entity2]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity1]]
    _tag = 'Entity1'

    [[Entities.Entity1]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.Entity0]]
    _tag = 'Entity0'

    [[Entities.Entity0]]
    _position = [ 0.0, 0.0, 0.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

[[Entities]]

    [[Entities.'Camera Entity']]
    _tag = 'Camera Entity'

    [[Entities.'Camera Entity']]
    _position = [ 0.0, 0.0, -5.0 ]
    _rotation = [ -0.0, 0.0, 0.0 ]
    _scale = [ 1.0, 1.0, 1.0 ]

    [[Entities.'Camera Entity']]
    _aspectRatio = 1.4444444179534912
    _fieldOfView = 70.0
    zFar = 0.10000000149011612
    zNear = 10000.0

